---
title: "Biostat 200C Homework 4"
subtitle: Due May 24  @ 11:59PM
author: "Ziheng Zhang_606300061"
date: today
format:
  html:
    theme: cosmo
    embed-resources: true
    number-sections: true
    toc: true
    toc-depth: 4
    toc-location: left
    code-fold: false
engine: knitr
knitr:
  opts_chunk: 
    fig.align: 'center'
    # fig.width: 6
    # fig.height: 4
    message: FALSE
    cache: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
```

## Q1. ELMR Excercise 7.5 (p150)
The debt data arise from a large postal survey on the psychology of debt. The frequency of credit card use is a three-level factor ranging from never, through occasionally to regularly.

### Q1.1
(a) Declare the response as an ordered factor and make a plot showing the relationship to prodebt. Comment on the plot. Use a table or plot to display the relationship between the response and the income group.

### Q1.2
(b) Fit a proportional odds model for credit card use with all the other variables as predictors. What are the two most significant predictors (largest t-values) and what is their qualitative effect on the response? What is the least significant predictor?

### Q1.3
(c) Fitaproportionaloddsmodelusingonlytheleastsignificantpredictorfromthe previous model. What is the significance of this predictor in this small model? Are the conclusions regarding this predictor contradictory for the two models?

### Q1.4
(d) Use stepwise AIC to select a smaller model than the full set of predictors. You will need to handle the missing values carefully. Report on the qualitative effect of the predictors in your chosen model. Can we conclude that the predictors that were dropped from the model have no relation to the response?

### Q1.5
(e) Compute the median values of the predictors in your selected model. At these median values, contrast the predicted outcome probabilities for both smokers and nonsmokers.

### Q1.6
(f) Fit a proportional hazards model to the same set of predictors and recompute the two sets of probabilities from the previous question. Does it make a differ- ence to use this type of model?

## Q2. Moments of exponential family distributions

Show that the exponential family distributions have moments
$$
\begin{eqnarray*}
  \mathbb{E}Y &=& \mu = b'(\theta) \\
  \operatorname{Var}Y &=& \sigma^2 = b''(\theta) a(\phi).
\end{eqnarray*}
$$

**Answer:**
In GLM, the distribution of $Y$ is from the exponential familty of distributions of form
$$
  f(y \mid \theta, \phi) = \exp \left[ \frac{y \theta - b(\theta)}{a(\phi)} + c(y, \phi) \right].
$$
We know that 
$$
  \int f(y) dy = \int \exp \left[ \frac{y \theta - b(\theta)}{a(\phi)} + c(y, \phi) \right] dy =1
$$
So we have
$$
\frac{\partial}{\partial \theta} \int f(y) dy = \int \frac{\partial}{\partial \theta} f(y) dy = 0
$$
Since 
$$
\frac{\partial}{\partial \theta} f(y) = \frac{y - b'(\theta)}{a(\phi)} f(y)
$$
So we have
$$
\begin{eqnarray*}
  0 &=& \int \frac{y - b'(\theta)}{a(\phi)} f(y) dy \\
  &=& \int \frac{y}{a(\phi)} f(y) dy - \int \frac{b'(\theta)}{a(\phi)} f(y) dy \\
  &=& \int y f(y) dy - b'(\theta) \int f(y) dy \\
  &=& \int y f(y) dy - b'(\theta) \\
  &=& \mathbb{E}Y - b'(\theta) = 0 \\
\mathbb{E}Y &=& b'(\theta)
\end{eqnarray*}
$$
Similarly, for variance, we have
$$
\begin{eqnarray*}
  \frac{\partial^2}{\partial \theta^2} \int f(y) dy &=& \int \frac{\partial^2}{\partial \theta^2} f(y) dy = 0 \\
  \frac{\partial^2}{\partial \theta^2} f(y) &=& \left(\frac{y - b'(\theta)}{a(\phi)}\right)^2 f(y)-\frac{b''(\theta)}{a(\phi)} f(y) \\
  0 &=& \int \left(\frac{y - b'(\theta)}{a(\phi)}\right)^2 f(y) dy - \int \frac{b''(\theta)}{a(\phi)} f(y) dy \\
 &=& \int (y - b'(\theta))^2 f(y) dy - \int b''(\theta)a(\phi) f(y) dy \\
 b''(\theta)a(\phi) &=& \int y^2 f(y) dy - 2b'(\theta) \int y f(y) dy + b'(\theta)^2 \int f(y) dy \\
 &=& \mathbb{E}Y^2 - 2b'(\theta) \mathbb{E}Y + b'(\theta)^2 \\
 &=& \mathbb{E}Y^2 - 2b'(\theta)^2 + b'(\theta)^2 \\
 &=& \mathbb{E}Y^2 - b'(\theta)^2 \\
 &=& \mathbb{E}Y^2-\mathbb{E}^2Y\\
 \operatorname{Var}Y &=& b''(\theta) a(\phi)
\end{eqnarray*}
$$
## Q3. Score and information matrix of GLM

Derive the gradient (score), negative Hessian, and Fisher information matrix (expected negative Hessian) of GLM.

**Answer:**
The log-likelihood function of GLM is
$$
\begin{eqnarray*}
  \ell(\boldsymbol{\beta}) &=& \sum_{i=1}^n \left[ \frac{y_i \theta_i - b(\theta_i)}{a(\phi)} + c(y_i, \phi) \right] \\
\end{eqnarray*}
$$
Since we have $\mu_i = b'(\theta_i)$, $\eta = g(\mu)$ and $\eta = \mathbf{x}^T \boldsymbol{\beta}$, then we have 
$$
\begin{eqnarray*}
\frac{\partial \theta_i}{\partial \mu_i} &=& \frac{1}{b''(\theta_i)}\\
\frac{\partial \mu_i}{\partial \eta_i} &=& \mu_i'(\eta_i)\\
\frac{\partial \eta_i}{\partial \boldsymbol{\beta}} &=& \mathbf{x}_i
\end{eqnarray*}
$$
So the gradient (score) is
$$
\begin{eqnarray*}
  \nabla \ell(\boldsymbol{\beta}) &=& \frac{\partial \ell(\boldsymbol{\beta})}{\partial \boldsymbol{\beta}}
  = \sum_{i=1}^n  \frac{\partial \ell(\boldsymbol{\beta})}{\partial \theta_i} \frac{\partial \theta_i}{\partial \mu_i} \frac{\partial \mu_i}{\partial \eta_i} \frac{\partial \eta_i}{\partial \boldsymbol{\beta}} \\
  &=& \sum_{i=1}^n \left[ \frac{y_i - b'(\theta_i)}{a(\phi)} \frac{\mu_i'(\eta_i)}{b''(\theta_i)} \mathbf{x}_i \right] \\
  &=& \sum_{i=1}^n \left[ \frac{(y_i - \mu_i)\mu_i'(\eta_i)}{\sigma_i^2} \mathbf{x}_i \right], \quad \text{since } \sigma_i^2 = a(\phi) b''(\theta_i)
\end{eqnarray*}
$$
So the negative Hessian is
$$
\begin{eqnarray*}
-\nabla^2 \ell(\boldsymbol{\beta}) &=& -\sum_{i=1}^n \frac{\mu_i'(\eta_i)}{\sigma_i^2} \mathbf{x}_i \frac{\partial (y_i - \mu_i)}{\partial \eta_i} \frac{\partial \eta_i}{\partial \boldsymbol{\beta}} -\sum_{i=1}^n  \frac{(y_i - \mu_i)}{\sigma_i^2} \frac{\partial \mu_i'(\eta_i)}{\partial \eta_i} \frac{\partial \eta_i}{\partial \boldsymbol{\beta}}\mathbf{x}_i \\
&& -\sum_{i=1}^n (y_i - \mu_i)\mu_i'(\eta_i) \mathbf{x}_i \frac{\partial}{\partial \mu_i}(\frac{1}{\sigma_i^2}) \frac{\partial \mu_i}{\partial \eta_i} \frac{\partial \eta_i}{\partial \boldsymbol{\beta}} \\
&=& \sum_{i=1}^n \frac{[\mu_i'(\eta_i)]^2}{\sigma_i^2} \mathbf{x}_i \mathbf{x}_i^T - \sum_{i=1}^n \frac{(y_i - \mu_i) \mu_i''(\eta_i)}{\sigma_i^2} \mathbf{x}_i \mathbf{x}_i^T \\
  & & + \sum_{i=1}^n \frac{(y_i - \mu_i) [\mu_i'(\eta_i)]^2 (d \sigma_i^{2} / d\mu_i)}{\sigma_i^4} \mathbf{x}_i \mathbf{x}_i^T
\end{eqnarray*}
$$
So the Fisher information matrix is
$$
 \mathbb{E} [- \nabla^2 \ell(\boldsymbol{\beta})] = \sum_{i=1}^n \frac{[\mu_i'(\eta_i)]^2}{\sigma_i^2} \mathbf{x}_i \mathbf{x}_i^T , \\
 \text{since } \sum_{i=1}^n \mathbb{E} (y_i - \mu_i) = 0 \text{ and others are constant for the second and third terms.}
$$

## Q4. ELMR Exercise 8.1 (p171)
Data is generated from the exponential distribution with density $f(y) = \lambda exp(−\lambda y)$ where $\lambda$, $y > 0$.

### Q4.1
(a) Identify the specific form of $\theta$, $\phi$, $a()$, $b()$ and $c()$ for the exponential distribution.

### Q4.2
(b) What is the canonical link and variance function for a GLM with a response following the exponential distribution?

### Q4.3
(c) Identify a practical difficulty that may arise when using the canonical link in this instance.

### Q4.4
(d) When comparing nested models in this case, should an F or $\chi^2$ test be used? Explain.

### Q4.5
(e) Express the deviance in this case in terms of the responses $y_i$ and the fitted values $\hat{\mu}_i$.
$$
\begin{eqnarray*}
D &=& 2 \sum(\frac{y_i-\hat{\mu}_i}{\hat{\mu}_i} - \log\frac{y_i}{\hat{\mu}_i})
\end{eqnarray*}
$$

## Q5. ELMR Exercise 8.4 (p172)
Consider the Galápagos data and model analyzed in this chapter. The purpose of this question is to reproduce the details of the GLM fitting of this data.

### Q5.1
(a) Fit a Poisson model to the species response with the five geographic variables as predictors. Do not use the endemics variable. Report the values of the coef- ficients and the deviance.

### Q5.2
(b) For a Poisson GLM, derive $\eta$, $\frac{d\eta}{d\mu}$, $V(\mu)$ and the weights to be used in an iteratively fit GLM. What is the form of the adjusted dependent variable here?

### Q5.3
(c) Using the observed response as initial values, compute the first stage of the iteration, stopping after the first linear model fit. Compare the coefficients of this linear model to those found in the GLM fit. How close are they?

### Q5.4
(d) Continue the iteration to get the next $\eta$ and $\mu$. Use this to compute the current value of the deviance. How close is this to the deviance from the GLM?

### Q5.5
(e) Compute one more iteration of the GLM fit, reporting the next calculation of the coefficients and deviance. How close are these to target now?

### Q5.6
(f) Repeat these iterations a few more times, computing the deviance in each time. Stop when the deviance does not change much. Compare your final estimated coefficients to that produced by the GLM fit.

### Q5.7
(g) Use your final iterated linear model fit to produce standard errors for the coefficients. How close are these to that produced by the direct GLM fit?

## Q6. ELMR Exercise 8.5 (p172)
Again using the Galápagos data, fit a Poisson model to the species response with the five geographic variables as predictors. Do not use the endemics variable. The purpose of this question is to compare six different ways of testing the significance of the elevation predictor, i.e., $H_0$: $\beta_{Elev}$ = 0. In each case, report the p-value.

### Q6.1
(a) Use the z-statistic from the model summary.

### Q6.2
(b) Fit a model without elevation and use the difference in deviances to make the test.

### Q6.3
(c) Use the Pearson Chi-squared statistic in place of the deviance in the previous
test.

### Q6.4
(d) Fit the Poisson model with a free dispersion parameter as described in Section 5.2. Make the test using the model summary.

### Q6.5
(e) Use the sandwich estimation method for the standard errors in the original model. Use these to compute z-statistics.

### Q6.6
(f) Use the robust GLM estimation method and report the test result from the summary.

### Q6.7
(g) Compare all six results. Pick the best one and justify your choice.

